src/components/MainContent/MainContent.jsx
src/components/MainContent/MainContent.module.css
src/components/PageContent/PageContent.jsx
src/components/PageContent/PageContent.module.css
src/components/PeriodSwitcher/PeriodSwitcher.jsx
src/components/PeriodSwitcher/PeriodSwitcher.module.css
src/components/Statistics/Statistics.jsx
src/components/Statistics/Statistics.module.css
src/components/StatsList/StatsList.jsx
src/components/StatsList/StatsList.module.css
src/pages/VideControlPage/VideControlPage.jsx
src/pages/VideControlPage/VideControlPage.module.css

Я зробив список статистикі і підєднав це все до сторінки відеоконтролю

create statistic list and conect components to VideoControllPage

---

src/components/CRMCalendar/CRMCalendar.jsx
src/components/CRMCalendar/CRMCalendar.module.css
src/components/Calendar/Calendar.jsx
src/components/Calendar/CalendarCrm.module.css
src/components/CalendarBlock/CalendarBlock.jsx
src/components/CalendarPagination/CalendarPagination.jsx
src/components/CalendarPagination/CalendarPaginationCrm.module.css
src/components/Chart/Chart.jsx
src/components/Chart/Chart.module.css
src/components/CreateAppointmentBtn/CreateAppointmentBtn.jsx
src/components/CreateAppointmentBtn/CreateAppointmentBtn.module.css
src/components/PeriodSelector/PeriodSelector.module.css

CRM calendar, correct blue grafic

Calendar10

---

package-lock.json
package.json
src/components/AppointmentBlock/AppointmentBlock.jsx
src/components/AppointmentGrid/AppointmentGrid.jsx
src/components/AppointmentGrid/AppointmentGrid.module.css
src/components/AppointmentTable/AppointmentTable.jsx
src/components/AppointmentTable/AppointmentTable.module.css
src/components/Calendar/Calendar.jsx
src/components/CalendarPagination/CalendarPagination.module.css
src/components/CalendarPagination/CalendarPaginationCrm.module.css
src/components/CarStatsChart/CarStatsChart.module.css
src/components/Chart/Chart.jsx
src/components/LoadStatsChart/LoadStatsChart.module.css
src/components/PeriodSelector/PeriodSelector.jsx
src/components/PeriodSelector/PeriodSelector.module.css

Calendar11

---

package-lock.json
package.json
src/components/AppointmentBlock/AppointmentBlock.jsx
src/components/AppointmentGrid/AppointmentGrid.jsx
src/components/AppointmentGrid/AppointmentGrid.module.css
src/components/AppointmentTable/AppointmentTable.jsx
src/components/AppointmentTable/AppointmentTable.module.css
src/components/Calendar/Calendar.jsx
src/components/Chart/Chart.jsx
src/components/PeriodSelector/PeriodSelector.jsx

add colors to calendar, change ticks for blue grafic(interval=1 where ticks<15 and interval=5 where ticks>15). add appointment

Calendar12

---

package-lock.json
src/components/Modals/ServiceBookingModal/ServiceBookingModal.jsx
src/pages/VideoControlPage/VideoControlPage.jsx
src/redux/cars/operations.js
src/redux/cars/slice.js
src/redux/crm/operations.js
src/redux/crm/selectors.js
src/redux/crm/slice.js
src/redux/initialState.js
src/redux/store.js
src/validationSchemas/ServiceBookingSchema.js

- operations (get records, create record, get posts and mechs, get visits)
- reducer,
- slice,
- selectors
- add dispatch of get mechs and posts to servicebooking modal

redux for crm + fix validation of serviceBookingModal

---

package-lock.json
src/components/AppointmentGrid/AppointmentGrid.jsx
src/components/AppointmentGrid/AppointmentGrid.module.css
src/components/AppointmentTable/AppointmentTable.jsx
src/components/AppointmentTable/AppointmentTable.module.css

add function for schedule, background

calendar13

---

src/components/AppointmentGrid/AppointmentGrid.jsx
src/components/AppointmentGrid/AppointmentGrid.module.css
src/components/AppointmentTable/AppointmentTable.jsx
src/components/Calendar/Calendar.jsx

fix CalendarCrm, add timeline, add scroll

Calendar14

---

src/components/AppointmentGrid/AppointmentGrid.jsx
src/components/AppointmentGrid/AppointmentGrid.module.css
src/components/ServiceStationDetailsAccordion/ServiceStationDetailsAccordion.jsx
src/components/ServiceStationDetailsTop/ServiceStationDetailsTop.jsx
src/components/ServiceStationDetailsTop/ServiceStationDetailsTop.module.css
src/components/ServiceStationDetailsTopTable/ServiceStationDetailsTopTable.jsx
src/components/ServiceStationDetailsTopTable/ServiceStationDetailsTopTable.module.css

fix timeline, add grid for serviceStationDetailsTop, add table ServiceStationDetailsTopTable

Calendar18

---

src/components/AppointmentGrid/AppointmentGrid.jsx
src/components/AppointmentGrid/AppointmentGrid.module.css
src/components/Calendar/Calendar.jsx
src/components/ServiceStationDetailsTop/ServiceStationDetailsTop.jsx

change calendar, change planner

Calendar19

---

src/components/AppointmentGrid/AppointmentGrid.jsx
src/components/AppointmentGrid/AppointmentGrid.module.css
src/components/CalendarPagination/CalendarPagination.jsx
src/components/CalendarPagination/CalendarPaginationCrm.module.css
src/components/ServiceStationDetailsAccordion/ServiceStationDetailsAccordion.jsx
src/components/ServiceStationDetailsAccordion/ServiceStationDetailsAccordion.module.css
src/components/ServiceStationDetailsTop/ServiceStationDetailsTop.jsx

fix planner? add button to ServiceStationDetailsTop

Calendar20

---

src/components/ServiceStationDetailsAccordion/ServiceStationDetailsAccordion.jsx
src/components/ServiceStationDetailsBottom/RatingPart/RatingPart.jsx
src/components/ServiceStationDetailsBottom/RatingPart/RatingPart.module.css
src/components/ServiceStationDetailsBottom/ServiceStationDetailsBottom.jsx

Calendar21

---

src/components/ServiceStationDetailsAccordion/ServiceStationDetailsAccordion.jsx
src/components/ServiceStationDetailsAccordion/ServiceStationDetailsAccordion.module.css
src/components/ServiceStationDetailsBottom/RatingPart/RatingPart.jsx
src/components/ServiceStationDetailsBottom/RatingPart/RatingPart.module.css
src/components/ServiceStationDetailsBottom/ServiceStationDetailsBottom.jsx

Calendar22

---

src/components/ConnectionsCircularPBSection/ConnectionsCircularPBSection.jsx
src/components/ConnectionsCircularPBSection/ConnectionsCircularPBSection.module.css
src/components/HorizontalPBSection/HorizontalPBSection.jsx
src/components/HorizontalPBSection/HorizontalPBSection.module.css
src/components/ServiceStationDetailsAccordion/ServiceStationDetailsAccordion.jsx
src/components/ServiceStationDetailsAccordion/ServiceStationDetailsAccordion.module.css
src/components/sharedComponents/CircleProgressBar/CircleProgressBar.jsx
src/components/sharedComponents/CircleProgressBar/CircleProgressBar.module.css
src/components/sharedComponents/ScheduleTable/ScheduleTable.jsx

add cancel to accordion, add linearprogress, add circleprogress

Calendar23

---

src/components/ClientsInWorkCircularPBSection/ClientsInWorkCircularPBSection.jsx
src/components/ClientsInWorkCircularPBSection/ClientsInWorkCircularPBSection.module.css
src/components/ConnectionsCircularPBSection/ConnectionsCircularPBSection.module.css
src/components/HorizontalPBSection/HorizontalPBSection.jsx
src/components/HorizontalPBSection/HorizontalPBSection.module.css
src/components/PageContent/PageContent.jsx
src/components/sharedComponents/CircleProgressBar/CircleProgressBar.jsx
src/components/sharedComponents/CircleProgressBar/CircleProgressBar.module.css

add circleprogressbar in clientsInWork, add toast in horizontalprogressBar

Calendar24

---

src/components/DistributorsCircularPBSection/DistributorsCircularPBSection.jsx
src/components/DistributorsCircularPBSection/DistributorsCircularPBSection.module.css
src/components/GeneralClientCircularPBSection/GeneralClientCircularPBSection.jsx
src/components/GeneralClientCircularPBSection/GeneralClientCircularPBSection.module.css
src/components/sharedComponents/CircleProgressBar/CircleProgressBar.jsx
src/components/sharedComponents/CircleProgressBar/CircleProgressBar.module.css

add circleprogressbar in generalclients and distributors

Calendar25

---

src/components/GeneralClientsListSection/GeneralClientsListSection.jsx
src/components/GeneralClientsListSection/GeneralClientsListSection.module.css
src/components/sharedComponents/RatingStars/RatingStars.jsx

add generalCkients,  add size stars to ratingstars

Calendar26

---

src/components/GeneralClientsListSection/GeneralClientsListSection.jsx
src/components/GeneralClientsListSection/GeneralClientsListSection.module.css

add sort in generalclients, add transition

Calendar27

---

src/components/HorizontalPBSection/HorizontalPBSection.jsx
src/components/HorizontalPBSection/HorizontalPBSection.module.css
src/components/sharedComponents/HorizontalProgressBar/HorizontalProgressBar.jsx
src/components/sharedComponents/HorizontalProgressBar/HorizontalProgressBar.module.css

add universal component HorisontalProgressBar, change HorizontalPBSection

Calendar28

---

src/components/Chat/Chat.module.css
src/components/Chat/RightSection/ChatAvto/ChatAvto.jsx
src/components/Chat/RightSection/ChatAvto/ChatAvto.module.css
src/components/Chat/RightSection/ChatFiles/ChatFiles.jsx
src/components/Chat/RightSection/ChatFiles/ChatFiles.module.css
src/components/Chat/RightSection/ChatHistoryChange/ChatHistoryChange.jsx
src/components/Chat/RightSection/ChatHistoryChange/ChatHistoryChange.module.css
src/components/Chat/RightSection/ChatNotes/ChatNotes.jsx
src/components/Chat/RightSection/ChatNotes/ChatNotes.module.css
src/components/Chat/RightSection/ChatSample/ChatSample.jsx
src/components/Chat/RightSection/ChatSample/ChatSample.module.css
src/components/Chat/RightSection/ChatTags/ChatTags.jsx
src/components/Chat/RightSection/ChatTags/ChatTags.module.css
src/components/Chat/RightSection/RightSection.jsx
src/components/Chat/RightSection/RightSection.module.css
src/components/ConnectionsCircularPBSection/ConnectionsCircularPBSection.module.css
src/components/DistributorsCircularPBSection/DistributorsCircularPBSection.module.css
src/components/GeneralClientCircularPBSection/GeneralClientCircularPBSection.module.css

fix style in circle progressbr, chat-rightsection - add empty component and accordion

Calendar29

---

src/components/Chat/RightSection/ChatSample/ChatSample.jsx
src/components/Chat/RightSection/ChatSample/ChatSample.module.css
src/components/Chat/RightSection/RightSection.jsx
src/components/Chat/RightSection/RightSection.module.css

add modal phone and notification, add button treeDots and function for her

Calendar32

---

src/components/ConnectionsCircularPBSection/ConnectionsCircularPBSection.jsx
src/components/ConnectionsMainComponent/ConnectionsMainComponent.jsx

add data to progressbar, change date on connection if change timefilter/

Calendar41

---

src/components/DashBoard/DashboardCharts/ClientsDynamicsChart/ClientsDynamicsChart.jsx
src/components/DashBoard/DashboardCharts/LtvChart/LtvChart.jsx
src/components/DashBoard/DashboardLeftSide/DashboardLeftSide.jsx
src/components/DashBoard/DashboardLeftSide/ProfitChart/ProfitChart.jsx
src/components/DashBoard/DashboardLeftSide/ProfitChart/ProfitChart.module.css

fix ltvchart, clientschart. add profitChart(green chart) in left side on dashboard

Calendar42

---

src/components/Accounting/ClientInWork/ClientsInWorkControlBarSection/ClientsInWorkControlBarSection.module.css
src/components/Accounting/ClientInWork/PaymentDistrModal/PaymentDistrModal.jsx
src/components/Accounting/ClientInWork/PaymentDistrModal/PaymentDistrModal.module.css
src/components/Accounting/ClientInWork/PaymentModal/PaymentModal.jsx
src/components/Accounting/ClientInWork/PaymentModal/PaymentModal.module.css
src/components/Accounting/ClientInWork/PopUp/PopUp.jsx
src/components/Accounting/ClientInWork/PopUp/PopUp.module.css

add PopUp, fix first number field

Calendar44
